# Generated by Django 5.2 on 2025-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='cost',
        ),
        migrations.AddField(
            model_name='patient',
            name='discount_category',
            field=models.CharField(choices=[('none', 'Без скидки'), ('pensioner', 'Пенсионер - 10%'), ('veteran', 'Ветеран - 15%'), ('disabled', 'Инвалид - 20%')], default='none', max_length=10, verbose_name='Категория скидки'),
        ),
        migrations.AddField(
            model_name='visit',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='Базовая стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)'),
        ),
    ]
