# Generated by Django 5.2 on 2025-04-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctor_expirience_patientprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='expirience',
            new_name='experience',
        ),
    ]
